apiVersion: 1

datasources:
  - name: InfluxDB-Sondes
    uid: P2C50AA8E2CDA95A6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ird
      defaultBucket: sondes
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}   # remplacer par votre token InfluxDB
    isDefault: true
    editable: true

